title: Logistics BPO Blog
description: Insights on Logistics Outsourcing, Freight Audit & Back Office

url: "https://backofficeoutsource.github.io"
baseurl: "/logisticsBPO"

markdown: kramdown
future: true

author:
  name: Logistics BPO
  email: info@infinity-logisticsbackoffice.com

permalink: "/:title/"
