title: Logistics BPO Blog
description: Insights on Logistics Outsourcing, Freight Audit & Back Office

url: "https://backofficeoutsource.github.io"
baseurl: "/logisticsBPO"

markdown: kramdown
future: true

plugins:

* jekyll-feed
* jekyll-sitemap

author:
name: Logistics BPO
email: [info@infinity-logisticsbackoffice.com](mailto:info@infinity-logisticsbackoffice.com)

# Clean URLs

permalink: /:title/
